# Use Python as the base image
FROM python:3.11-slim

# Set a working directory inside the container
WORKDIR /app

# Copy files from this folder into the container
COPY app.py .

# Run a command when the container starts
CMD ["python", "app.py"]

